### ISSUE TITLE
send Content-Length in the headers?

### ISSUE THREAD

**Issue by mansouralex** [Vinelab/http#11]
How to send Content-Length in the headers when you send request, also how to decide the Content-Type?

**Comment by Mulkave** [comment]
you may send the headers as [mentioned in the docs](https://github.com/Vinelab/http#headers):

```php
$response = HttpClient::get([
    'url' => 'http://some.where.url',
    'headers' => ['Content-Length: 12345', 'Content-Type: application/json']
]);
```
