### ISSUE TITLE
Requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by messi89** [Vinelab/http#23]
Hi

I can't install the package on the latest laravel version
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vinelab/http v1.5.0 requires tolerance/tolerance ^0.3.3 -> satisfiable by tolerance/tolerance[0.3.3].
    - vinelab/http v1.5.1 requires tolerance/tolerance ^0.3.3 -> satisfiable by tolerance/tolerance[0.3.3].
    - vinelab/http v1.5.2 requires tolerance/tolerance ^0.3.3 -> satisfiable by tolerance/tolerance[0.3.3].
    - Conclusion: don't install tolerance/tolerance 0.3.3
    - Installation request for vinelab/http ^1.5 -> satisfiable by vinelab/http[v1.5.0, v1.5.1, v1.5.2].

Installation failed, reverting ./composer.json to its original content.
`

Laravel 5.3.*

**Comment by harris21** [comment]
Hello @messi89,

I have just used a fresh Laravel installation `v5.3.28`, which is the latest version at the moment, and by using `composer require vinelab/http` I was able to install the Http package without any errors.

**Comment by messi89** [comment]
reinstalled new version solved the issue

thanks

**Comment by harris21** [comment]
Cheers!
